server:
  port: 6224

spring:
  application:
    name: stonehiy-config
  cloud:
    config:
      server:
        git: #这是其他项目配置文件的git仓库地址
          uri: https://github.com/stonehiy/springcloud.git
          searchPaths: 'my' #配置仓库路径
          label: master #配置仓库的分支
          username: '' #访问git仓库的用户名
          password: '' #访问git仓库的用户密码



eureka:
  client:
    service-url: #注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: http://root:root@127.0.0.1:8888/eureka
    instance:
      prefer-ip-address: true #可能比较长，复制的时候请写在一行
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
      appname: stonehiy-config

security:
  basic:
    enabled: true
  user:
      #这是config-server的用户名和密码
      name: root
      password: root